config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :users, param: :slug, only: [:show, :index, :new, :create, :update, :edit, :destroy] do
    member do
      get :following, :followers
    end
  end

  resources :lists, only: [ :index, :show, :create, :edit, :new, :update ] do
    resources :list_places, only: [:create, :destroy]
    resources :favourites
  end

  resources :places, only: [:show, :update, :edit, :destroy, :index]

  #resources :listplaces, only: [:new, :create, :destroy]
  resources :favourites, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: [:create, :destroy]
  delete 'lists/:id', to: 'lists#destroy', as: 'delete_list'

  resources :reservations, only: [:show, :edit, :create, :destroy]
  resources :notifications, only: [:index, :show]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :photo, PhotoUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]


  has_many :favourites, dependent: :destroy
  has_many :lists, dependent: :destroy

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  before_validation :to_slug

  validates :email, uniqueness: true
  validates :username, uniqueness: true

  # Follow a user
  def follow(other_user)
    following << other_user
  end

  # Unfollow a user
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  def add_slugs
    update(slug: to_slug)
  end

  def to_param
    slug
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.name.slice(0, 14)
      user.photo = auth.info.image
      # user.username = "user" + "#{(0..9).sample}" + "#{(a..z).sample}"
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end



  private

  def to_slug
    self.slug = username.parameterize.truncate(80, omission: '')
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user # event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to root_path
    end
  end

  def failure
    redirect_to new_user_session_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]
  skip_before_action :authenticate_user!, only: [:show]

  def show
  end

  def new
  end

  def index
    @users = User.all
  end

  def create
    #User.create(slug: to_slug(:username))
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to current_user
    else
      render :edit
    end
  end


  def edit
  end

  def destroy
  end

  private

  def find_user
    @user = User.find_by(slug: params[:slug])
    # authorize @user
  end

  def user_params
    params.require(:user).permit(:username, :photo, :slug,
                                 :full_name, :email, :location, :bio, :twitter, :facebook, :instagram, :website)
  end
end

app/views/users/SHOW DEMO.html.erb
<div class = "list-container user-profile-container user-wrapper">

  <div class = "user-profile-inner-container d-inline-flex">

    <p><strong>Username:  </strong>  <%=@user.username %></p>
    <p><strong>Name:  </strong>  <%=@user.full_name %></p>
    <p><strong>Bio:  </strong>  <%=@user.bio %></p>
    <p><strong>Social Media:  </strong>  <%=@user.instagram%> <%=@user.facebook%> <%=@user.twitter%></p>
    <p><strong>Personal Website: </strong>  <%=@user.website %></p>
    <p><%= cl_image_tag(@user.photo.url, width: 300, height: 300, crop: :fill) unless @user.photo.url.nil? %></p>

    <%= link_to "Edit user", edit_user_path %>

  <div><%= render 'follow_form' if user_signed_in? %></div>
</div>
  <div class="container">
  <div class="row">
    <% @user.lists.each do |list| %>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <%= link_to "", list_path(list)%>
      <div class="card" id = "card-custom-attributes" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.1)), url('<%= list.photo.url.nil? ? "placeholder" : cl_image_path(list.photo.url, width: 400, height: 500, crop: :fill) %>')" >
        <%= link_to "", list_path(list), class: 'card-link' %>
        <div class = "card-text-bottom">
          <div class="card-avatar"></div>
          <div class="card-content" style="">
            <%= list.name %>
          </div>
          <div class="card-likes">
            <span class="glyphicon glyphicon-heart"><% if list.favourites.nil? %> 0 Likes <% else %>
              <%= list.favourites.count %> <%= (list.favourites.count) == 1 ? 'Like' : 'Likes'%>
              <% end %>
            </span>
          </div>
        </div>

      </div>
    </div>
    <% end %>

  </div>
</div>

 <br><br><br><br>



<div class="container headline-container">
  <strong><p>My favorites</p></strong>
  <div class="row">
    <% @user.favourites.each do |fav| %>
    <% list = fav.list%>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <%= link_to "", list_path(list)%>
      <div class="card" id = "card-custom-attributes" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.1)), url('<%= list.photo.url.nil? ? "placeholder" : cl_image_path(list.photo.url, width: 400, height: 500, crop: :fill) %>')" >
        <%= link_to "", list_path(list), class: 'card-link' %>
        <div class = "card-text-bottom">
          <div class="card-avatar"></div>
          <div class="card-content" style="">
            <%= list.name %>
          </div>
          <div class="card-likes">
            <span class="glyphicon glyphicon-heart"><% if list.favourites.nil? %> 0 Likes <% else %>
              <%= list.favourites.count %> <%= (list.favourites.count) == 1 ? 'Like' : 'Likes'%>
              <% end %>
            </span>
          </div>
        </div>

      </div>
    </div>
    <% end %>
  </div>
</div>


  <!-- </div> -->
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-primary" %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class='form-container'>
  <div class='container-headline'>
      <h1>Edit Profile</h1>
      <div class='inner-form-container'>
        <div class='form-container-arrangement'>


          <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :full_name %>
            <%= f.text_field :full_name, class: 'form-control' %>
          </div>

           <div class="form-group">
            <%= f.label :username %>
            <%= f.text_field :username, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :location %>
            <%= f.text_field :location, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :bio %>
            <%= f.text_area :bio, :rows => 5, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :photo %>
            <%= f.file_field :photo, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :facebook %>
            <%= f.text_field :facebook, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :twitter %>
            <%= f.text_field :twitter, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :instagram %>
            <%= f.text_field :instagram, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :website %>
            <%= f.text_field :website, class: 'form-control' %>
          </div>

          <div class='form-group'> <%= f.submit class: 'btn btn-info'%></div>

          <div class='delete-link form-group'><%= link_to 'Delete Account', lists_path,
          method: :delete,
          data: { confirm: "Are you sure?" } , class: 'btn btn-info' %>
        </div>

        <div class='link-back form-group'><%= link_to "Back to Profile", user_path(@user), class: 'btn btn-info' %></div>

        <% end %>
    </div>
  </div>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1>Search Setting</h1>
  <h2>this will be used to search for users, live feed of activities, search for coupouns/offers</h2>

  <div class="avatar">
    <% @users.each do |user| %>
    <div class="avatar">
      <%= cl_image_tag (user.photo) %>
      </div>
    <% end %>
  </div>

</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class = "user-profile-container">

    <!-- first section contains profile photo and bio section -->
    <div class="row justify-content-center section top-section">
      <!-- profile picture -->
      <div class="photo col-sm-5">
        <%= cl_image_tag(@user.photo.url, width: 300, height: 300, crop: :fill) unless @user.photo.url.nil? %>
      </div>

      <!-- bio section -->
      <div class="col-sm-7 bio-section">
        <!-- name, username and edit button -->
        <div class="container">
          <div class="row">
            <div class="col-12 center title">
              <p class="name"><strong><%=@user.full_name.titleize if @user.full_name %></strong></p>
            </div>
            <div class="col-12 center title" >
              <p class="handle">@<%=@user.username %></p>
            </div>
          </div>

          <div class="row bio-box">
            <div class="col-12">
              <p><%= @user.bio %></p>
            </div>
            <div class="col-12">
              <ul>
                <!-- would be better code to make a helper method instead of doing ruby calculations in the view -->
                <% if @user.facebook.present? %>
                <li><a href="<%= "http://www.facebook.com/" + @user.facebook %>" target="_blank"> <i class="clickable fab fa-facebook-square"></i></a></li>
                <% end %>
                <% if @user.instagram.present? %>
                <li><a href="<%= "http://www.instagram.com/" + @user.instagram %>" target="_blank"> <i class="clickable fab fa-instagram"></i></a></li>
                <% end %>
                <% if @user.twitter.present? %>
                <li><a href="<%= "http://www.twitter.com/" + @user.twitter %>" target="_blank"> <i class="clickable fab fa-twitter"></i></a></li>
                <% end %>
                <% if @user.website.present? %>
                <li><a href="<%= "http://" + @user.website %>" target="_blank"><i class="clickable fas fa-globe-americas"></i></a></li>
                <% end %>
              </ul>
            </div>
            <div class="follow">
              <div><%= render 'follow_form' if user_signed_in? %></div>
              <div>
                <% if current_user && @user.id == current_user.id %>
                  <div> <%= link_to "Edit Profile", edit_user_path, class: 'btn-link clickable-grey' %></div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- second section contains lists that are owned by user and lists that are liked/followed by user -->

      <!-- lists owned by user -->
      <div class="list-section">
        <div class="container headline-container">
          <% if !(@user.lists.nil?) %>
          <strong><p id='mylist'>Workshop's On Offer</p></strong>
          <div class="row">
            <% @user.lists.each do |list| %>
            <div class="col-xs-12 col-sm-6 col-md-4">
            <%= render 'shared/card', list: list %>
            </div>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>

      <!-- lists followed/liked by user -->
      <div class="list-section">
        <div class="container headline-container">
          <strong><p id='myfavs'> <%= @user.username.capitalize %>'s Favorites</p></strong>
          <div class="row">
            <% @user.favourites.each do |fav| %>
            <% list = fav.list%>
            <div class="col-xs-12 col-sm-6 col-md-4">
              <%= link_to "", list_path(list)%>
               <%= render 'shared/card', list: list %>
              <% end %>

            </div>
          </div>
        </div>
      </div>

            <div class="card-product">
              <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
              <div class="card-product-infos">
                <h2>Class Pass Reservation token</h2>
                <p>Product description <strong>date time</strong> and how ppl</p>
                <p>link 'here' to send user a message</p>
              </div>
            </div>

</div>
  <!--   third section contains map -->
  <!--   <div class="row justify-content-center section">
      <div class="col-6">
        <h3>MAP</h3>
      </div>
    </div>
  </div>
 -->

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>