config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :users, param: :slug, only: [:show, :index, :new, :create, :update, :edit, :destroy] do
    member do
      get :following, :followers
    end
  end

  resources :lists, only: [ :index, :show, :create, :edit, :new, :update ] do
    resources :list_places, only: [:create, :destroy]
    resources :favourites
  end

  resources :places, only: [:show, :update, :edit, :destroy, :index]

  #resources :listplaces, only: [:new, :create, :destroy]
  resources :favourites, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: [:create, :destroy]
  delete 'lists/:id', to: 'lists#destroy', as: 'delete_list'

  resources :reservations, only: [:show, :edit, :create, :destroy]
  resources :notifications, only: [:index, :show]

end

app/views/shared/_card.html.erb
<div class="card" id = "card-custom-attributes" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.1)), url('<%= list.photo.url.nil? ? "placeholder" : cl_image_path(list.photo.url, width: 400, height: 500, crop: :fill) %>')" >
  <%= link_to "", list_path(list), class: 'card-link' %>
  <div class = "card-text-bottom">
    <div class="card-content">
      <div class ="card-name">
        <h3><%= list.name %></h3>
        <p hidden id = "card-date"><%= list.created_at%></p>
        <h4 class="bold"><%= list.category %></h4>
        <p><%= list.description %></p>
      </div>
      <div class="card-likes">
        <div class="card-heart-position" id="like-container-<%= "#{list.id}"%>">
          <% if !list.favourites.nil? && current_user%>
          <% pre_like = list.favourites.find { |like| like.user_id == current_user.id} %>

          <% if pre_like %>
          <%= render 'shared/dislike', list: list, pre_like: pre_like %>
          <% else %>
          <%= render 'shared/like', list: list %>
          <% end %>

          <% else %>
          <%= render 'shared/like', list: list %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_dislike.html.erb
<%= link_to list_favourite_path(list, pre_like), method: :delete, id: 'dislike-button', class: 'pulse animated infinite', remote: true  do %>
  <i class="fas fa-heart pulse animated"></i>
<% end %>

app/views/shared/_dropdown-sort.html.erb
<div class="btn-group" id ="btn-group-id">
<button class="btn btn-simple" type="button" id="sort-by-label" disabled>
    Sort by:
</button>

<div class="dropdown" id="sort-by-dropdown">
  <button class="btn btn-create dropdown-toggle" id="current-sort-by" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Likes
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Likes</a>
    <a class="dropdown-item" href="#">Upcoming</a>
    <a class="dropdown-item" href="#">Location (nearest-to-you)</a>
    <a class="dropdown-item" href="#">Category</a>
    <a class="dropdown-item" href="#">Price</a>
  </div>
</div>
</div>

<%= javascript_pack_tag 'plugins/dropdown' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" <%="id=footer-list-show" if !params[:id].nil? %> >
  <div class="footer-copyright">
    © Hobby Horse Prototypo by Harrison Davies
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-facebook"></i>Contact</a>
  </div>
</div>

app/views/shared/_like.html.erb
<%= link_to list_favourites_path(list), method: :post, id: 'like-button', class: 'pulse animated', remote: true do %>
  <i class="far fa-heart pulse animated"></i>
<% end %>

app/views/shared/_likecount.html.erb
<%= element.favourites.count %> <%= (element.favourites.count) == 1 ? 'Like' : 'Likes' %>

app/views/shared/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create a Workshop!</h5>
      </div>
      <div class="modal-body">
        <%= simple_form_for(List.new, html: {type: "html", data: {controller: "submit" }} ) do |form| %>
        <%= form.input :name, as: :string, input_html: {class: "count-char"}, label: 'Give it a name:', placeholder: "Hell's Kitchen, Ricky's Bar", required: true, html:{ data: {charLimit: "50"}}, maxlength: "50" %>
        <div class="form-helper-info">
          <span class="form-helper-error" data-error="Be sure to field out this field"></span>
          <span class="form-helper-number" data-charLimit="50" id="counter-list_name"></span>
        </div>
        <%= form.input :category, label: "Select a best fit:" , as: :radio_buttons, collection: ['Art', 'Business Skills', 'Crafts', 'Dance', 'Drinks and Tasting', 'Food', 'Health and Beauty', 'Languages', 'Mindfulness and Wellbeing', 'Music', 'Photography', 'Technology', 'Sports','Other'], wrapper: :vertical_collection_inline %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn-info ">
              <%= form.button :submit, "Start!", data: { disable_with: false } %>
        </button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand navbar-light navbar-lewagon my-nav-bar">

      <div class="flex-one">
      <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag ("logo.png") %>
      <% end %>
      </div>

      <div class="collapse navbar-collapse flex-two" id="navbarSupportedContent">
         <ul class="navbar-nav mr-auto topnav">
            <% if user_signed_in? %>
               <li class="nav-item nav-click">
                <%= link_to "Find", places_path, class: "nav-link navred" %>
               </li>
                  <li class="nav-item nav-click" >
                    <%= link_to "Post", places_path, class: "nav-link navyellow nav-link-create-list", "data-toggle" => "modal", 'data-target' => '#exampleModal' %>
                  </li>
                     <li class="nav-item nav-click" >
                          <%= link_to "Search", users_path, class: "nav-link navgreen" %>
                     </li>
                        <li class="nav-item nav-click" >
                          <%= link_to current_user.username.capitalize, user_path(current_user), class: "nav-link navblue" %>
                        </li>
      </div>

      <div class="nav-restrain dropdown flex-one">
                             <%= cl_image_tag ("HH.png"), class: "hh-logo dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                              <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
                                 <%= link_to "Reservations", "#", class: "dropdown-item" %>
                                  <%= link_to "Credits", "#",  class: "dropdown-item" %>
                                 <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                               </div>

         </ul>

               <% else %>


                    <div class="loged-out">
                      <ul>
                        <li class="nav-restrain  flex-two">

                            <%= image_tag ("HH.png") %>
                        </li>
                              <div class="flex-one nav-info">
                                 <li class="nav-item active">
                                     <%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
                                  <li class="nav-item">
                                     <%= link_to "Register", new_user_registration_path, class: "nav-link" %></li>
                               </div>
                      </ul>
                    </div>

                <% end %>
      </div>
</div>


<%= render 'shared/modal' %>

app/views/shared/_share.html.erb
_share.html.erb