config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :users, param: :slug, only: [:show, :index, :new, :create, :update, :edit, :destroy] do
    member do
      get :following, :followers
    end
  end

  resources :lists, only: [ :index, :show, :create, :edit, :new, :update ] do
    resources :list_places, only: [:create, :destroy]
    resources :favourites
  end

  resources :places, only: [:show, :update, :edit, :destroy, :index]

  #resources :listplaces, only: [:new, :create, :destroy]
  resources :favourites, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: [:create, :destroy]
  delete 'lists/:id', to: 'lists#destroy', as: 'delete_list'

  resources :reservations, only: [:show, :edit, :create, :destroy]
  resources :notifications, only: [:index, :show]

end

app/models/list_place.rb
class ListPlace < ApplicationRecord
  belongs_to :list
  belongs_to :place
  validates_presence_of :list
  validates_presence_of :place
  accepts_nested_attributes_for :place
end

app/controllers/list_places_controller.rb
class ListPlacesController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @list_place = ListPlace.new(listplace_params)
    @list_place.list = @list
    #@list_place.place = Place.new(place_params)

    @list_place.save

    respond_to do |format|
      format.html { redirect_to edit_list_path(@list) }
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end

  end

  def destroy
    @list = List.find(params[:list_id])
    @list_place = ListPlace.find(params[:id])
    @list_place.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to edit_list_path(@list)
  end

  private

  def listplace_params
    params.require(:list_place).permit(:comments, :attendence, place_attributes: [:name, :address, :photo, :photo_cache, :latitude, :longitude, :phone, :city, :start_time, :length, :capacity, :description, :title, :price])
  end
end

app/views/list_places/_delete.html.erb
<%= link_to "Delete",  list_list_place_path(list, list_place),
      method: :delete,
      data: { confirm: "Are you sure?" }, class: "btn btn-danger " %>

app/views/list_places/_form.html.erb
<%= simple_form_for([ list, list_place], remote: true, html: {data: {controller: "submit2"}}) do |form| %>

  <%= form.simple_fields_for :place do |j| %>
      <%= j.input :title, label: "Name your Class:",placeholder: "Workout With Lexy's Sister", as: :string, label_html: { class: 'form' }, input_html: {class: "count-char"}, required: true, maxlength: "50"%>
      <div class="form-helper-info">
        <span class="form-helper-error" data-error="Be sure to field out this field"></span>
        <span class="form-helper-number" data-charLimit="50" id="counter-list_place_place_attributes_title"></span>
      </div>
      <%= form.input :comments, placeholder: "Workshop's goal", as: :text , label: "Description", label_html: { class: 'form' }, :input_html => {:rows => 1, class: "count-char"}, required: true, maxlength: "200"%>
      <div class="form-helper-info">
        <span class="form-helper-error" data-error="Be sure to field out this field"></span>
        <span class="form-helper-number" data-charLimit="200" id="counter-list_place_comments"></span>
      </div>
      <%= j.input :name, placeholder: 'Where can we find it?', label: "Location", label_html: { class: 'form' }, :input_html => { :id => "autocomplete" }, required: true%>
      <div class="form-helper-info">
        <span class="form-helper-error" data-error="Be sure to field out this field"></span>
      </div>
      <%= j.input :address, label_html: { class: 'form' }, :input_html => { :id => "full_address" } , as: :hidden%>
      <%= j.input :latitude, label_html: { class: 'form' },  :input_html => { :id => "latitude" } , as: :hidden%>
      <%= j.input :longitude, label_html: { class: 'form' }, :input_html => { :id => "longitude" } , as: :hidden%>

   <div class="place-setting">
      <h3>Prices and Capacity</h3>
      <div class="place-pricecapacity">
        <%= j.input :start_time, as: :string, label: "Select a Date:", label_html: { class: 'form' },  required: true%>
        <div class="form-helper-info">
          <span class="form-helper-error" data-error="Be sure to field out this field"></span>
        </div>
        <div class="row d-flex align-items-center">
            <div class="col-sm-4 d-flex justify-content-center align-items-center">
                <%= j.input :length, as: :tel, label: "Duration:", input_html: {class: ""}, required: true%>
            </div>
            <div class="col-sm-4  d-flex justify-content-center align-items-center">
            <%= j.input :capacity, input_html: {class: "only-numeric"}, as: :tel, label: "Capacity:", required: true%>
            </div>
            <div class="col-sm-4  d-flex justify-content-center align-items-center">
              <%= j.input :price, as: :tel,  input_html: {class: "only-numeric"},  label: "Price in USD:",  required: true%>
            </div>
          </div>
      </div>
   </div>
   <div class="d-flex flex-column  align-items-center justify-content-center mt-2">
    <h6>lastly, the class needs a cover photo</h6>
    <%= j.input :photo, required: true, label: 'Upload class cover photo!', :label_html => { :class => 'input-label' } %>
    <%= j.input :photo_cache,required: true, as: :hidden, data: {target: "submit2.photoInput"} %>
   </div>
<% end %>
    <h6 class="text-center">When you're form is filled out, add the class to preview it before saving it.</h6>
    <div class = 'text-center mt-2'><%= form.submit 'Add class to workshop!', class: 'btn-info' %> </div>
    <div class="diveder">.</div>
<% end %>

app/views/list_places/_show.html.erb
<div class="container border mt-3">
  <%= cl_image_tag lp.place.photo, crop: :scale, class: 'place-image rounded' %>
  <h6 class="text-center mt-2"><%=lp.place.title%></h6>
  <p class="text-center text-secondary"><%=lp.place.name%></p>
  <div class="d-flex flex-column justify-content-center align-items-center">
    <div class="d-flex flex-row justify-content-between align-items-center w-100">
      <p>Capacity:</p>
      <p><strong><%=lp.place.capacity%></strong>  people</p>
    </div>
    <div class="d-flex flex-row justify-content-between w-100">
      <p>Price:</p>
      <p><strong>$<%=lp.place.price%></strong></p>
    </div>
  </div>
  <p class="text-center">start time</p>
  <p class="text-center text-secondary"><%=lp.place.start_time%></p>
  <div class="d-flex align-items-center justify-content-center">
     <p><%= render 'list_places/delete', list_place: lp, list: list%></p>
  </div>
</div>

app/views/list_places/create.html.erb
<h1>Listplaces#create</h1>
<p>Find me in app/views/listplaces/create.html.erb</p>

app/views/list_places/create.js.erb
// function refreshForm(listPlaceHTML) {
//   const newListForm = document.getElementById('new_list_place');
//   console.log(newListForm);
//   console.log(listPlaceHTML);
//   newListForm.innerHTML = listPlaceHTML;
// }

function refreshForm() {

  //const inputs = document.querySelectorAll('.form-control');
  const inputs = document.getElementById('autocomplete');
  inputs.value = "";
  const inputs2 = document.getElementById('list_place_comments');
  inputs2.value = "";
  const inputs3 = document.getElementById('list_place_place_attributes_photo');
  inputs3.value = "";
}

function addListPlace(listPlaceHTML) {
  const places = document.getElementById('places');
  places.insertAdjacentHTML('beforeend', listPlaceHTML);
}



addListPlace('<%= j render "list_places/show", list: @list, lp: @list_place%>');

let photo = document.querySelector('#list_place_place_attributes_photo');

let placeholders = document.querySelectorAll(".place-image");

let placeholder = placeholders[placeholders.length - 1];

if (photo.files[0]) {
  let reader = new FileReader();
  reader.onload = (event) => {
    placeholder.src = event.target.result;
  };
  reader.readAsDataURL(photo.files[0]);
}

refreshForm();

window.scrollTo(0,document.body.scrollHeight);

// refreshForm('<%= j render "list_places/form", list: @list, list_place: ListPlace.new()%>');

// const addListenerToPhoto = () => {
//  const photo = document.querySelector('#list_place_place_attributes_photo')
//  photo.addEventListener("change", (event) => {
//    const image = event.target.files[0];
//    console.log("chnge event is triggered yoooo");
//    const placeholders = document.querySelector("place-image");
//    const placeholder = placeholders[placeholders.length - 1];
//    const reader = new FileReader();
//    reader.onload = (event) => {
//      placeholder.src = event.target.result;
//    };
//    reader.readAsDataURL(image);
//  });
// };

app/views/list_places/destroy.html.erb
<h1>Listplaces#destroy</h1>
<p>Find me in app/views/listplaces/destroy.html.erb</p>

app/views/list_places/new.html.erb
<h1>Listplaces#new</h1>
<p>Find me in app/views/listplaces/new.html.erb</p>