config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :users, param: :slug, only: [:show, :index, :new, :create, :update, :edit, :destroy] do
    member do
      get :following, :followers
    end
  end

  resources :lists, only: [ :index, :show, :create, :edit, :new, :update ] do
    resources :list_places, only: [:create, :destroy]
    resources :favourites
  end

  resources :places, only: [:show, :update, :edit, :destroy, :index]

  #resources :listplaces, only: [:new, :create, :destroy]
  resources :favourites, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: [:create, :destroy]
  delete 'lists/:id', to: 'lists#destroy', as: 'delete_list'

  resources :reservations, only: [:show, :edit, :create, :destroy]
  resources :notifications, only: [:index, :show]

end

app/models/place.rb
class Place < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :list_places, dependent: :destroy, inverse_of: :place
  has_and_belongs_to_many :lists, through: :list_places

  validates :name, presence: true
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def show
  end

  def new
    @place = Place.new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
    @places = Place.all
  end

  private

  def find_place
    @place = Place.find(params[:id])
    #authorize @list
  end

  def place_params
    params.require(:place).permit(:name, :address, :comment, :phone, :city, :start_time, :length, :capacity, :description, :title, :price)
  end
end

app/views/places/_place-cards.html.erb
"" <div class="row">
  <% @places.each do |p| %>
  <div class="col">
    <div class="card mt-2">
        <div class="card-container-location">
          Country: Monte Negro City: Podgorica
        </div>
         <div class="card-img" style="background: url('<%= p.photo.url.nil? ? "placeholder" : cl_image_path(p.photo.url, crop: :fill) %>')no-repeat center center; background-size: cover;" ></div>
         <div class="card-container-title">
            Lorem ipsum dolor sit amet, consectetuer adipiscin
         </div>
         <div class="card-container-info">
            <div class="d-flex flex-column justify-content-between">
                <div class="card-content-infoCard">
                    duration: 24 hours
                </div>
                <div class="card-content-infoCard">
                    capacity: 100 people
                </div>
            </div>
            <div class="d-flex flex-column justify-content-between h-100">
                <div class="card-content-infoCard">
                    category: cooking
                </div>
                <div class="card-content-infoCard">
                    cost: 1000 credits
                </div>
            </div>
         </div>
         <div class="card-container-infoFooter">
            <div class="card-container-clickableInfo">
              <div class="card-container-footerInfo">
                <i class=" text-danger far fa-heart"></i>
                like
              </div>
              <div class="card-container-footerInfo">
                <i class=" text-danger far fa-share-square"></i>
                like
              </div>
              <div class="card-container-footerInfo">
                <i class=" text-danger far fa-paper-plane"></i>
                contact host
              </div>
            </div>
            <div class="card-container-reviews">
              <div class="card-container-footerInfo">
                <i class=" text-info far fa-star"></i>
                4.9
              </div>
            </div>
         </div>
         <div class="btn btn-danger btn-lg btn-block w-100">
           reserve
         </div>
    </div>
  </div>
  <% end %>
</div>

app/views/places/create.html.erb
<h1>Places#create</h1>
<p>Find me in app/views/places/create.html.erb</p>

app/views/places/destroy.html.erb
<h1>Places#destroy</h1>
<p>Find me in app/views/places/destroy.html.erb</p>

app/views/places/edit.html.erb
<h1>Places#edit</h1>
<p>Find me in app/views/places/edit.html.erb</p>

app/views/places/index.html.erb
<div class="container">
  <h1>Sign UP to ongoing classes</h1>
  <div class="container">
    <%= render 'place-cards' %>
  </div>
</div>

app/views/places/new.html.erb
<h1>Places#new</h1>
<p>Find me in app/views/places/new.html.erb</p>

<%= simple_form_for(@place, url: list_places_path) do |f| %>
  <!-- [...] -->
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.submit 'Create Workshop', class: 'btn btn-info'%>
  <!-- [...] -->
<% end %>

app/views/places/show.html.erb
<h1>Places#show</h1>
<p>Find me in app/views/places/show.html.erb</p>

app/views/places/update.html.erb
update.html.erb